//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-04/09/2009 09:05 AM(mockbuild)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.17 at 09:57:44 AM CDT 
//


package mx.uaemex.redalyc.XMLarticulos;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.uaemex.redalyc.XMLarticulos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.uaemex.redalyc.XMLarticulos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TUrl }
     * 
     */
    public TUrl createTUrl() {
        return new TUrl();
    }

    /**
     * Create an instance of {@link Urlset }
     * 
     */
    public Urlset createUrlset() {
        return new Urlset();
    }

}
